package modeled

import (
	"math/rand"
	"time"
)

// BandwidthInterval describes one contiguous time slice of constant bandwidth.
type BandwidthInterval struct {
	DurationMs    int
	BandwidthMbps float64
}

// BandwidthTrace models time-varying available bandwidth using a sequence of
// constant-rate intervals. It is typically generated by a 3-state Markov chain
// (low/medium/high) but can also be supplied directly for replay of real
// traces in later phases.
type BandwidthTrace struct {
	intervals []BandwidthInterval
}

// NewBandwidthTrace constructs a trace from an explicit interval list.
func NewBandwidthTrace(intervals []BandwidthInterval) *BandwidthTrace {
	return &BandwidthTrace{intervals: intervals}
}

// NewSyntheticTrace generates a synthetic trace via a 3-state Markov chain.
// variability is the fractional spread from the mean: at 0.4, low=0.6*base
// and high=1.4*base. durationSec controls the total trace length.
func NewSyntheticTrace(durationSec int, baseBandwidthMbps float64, variability float64, rng *rand.Rand) *BandwidthTrace {
	if variability == 0 {
		return &BandwidthTrace{intervals: []BandwidthInterval{{
			DurationMs:    durationSec * 1000,
			BandwidthMbps: baseBandwidthMbps,
		}}}
	}
	low := baseBandwidthMbps * (1 - variability)
	med := baseBandwidthMbps
	high := baseBandwidthMbps * (1 + variability)
	// Transition rows: LOW, MED, HIGH.
	trans := [3][3]float64{
		{0.7, 0.25, 0.05},
		{0.15, 0.7, 0.15},
		{0.05, 0.25, 0.7},
	}
	state := 1 // start in MED
	bw := []float64{low, med, high}
	var intervals []BandwidthInterval
	elapsed := 0
	target := durationSec * 1000
	for elapsed < target {
		// Duration of this state: 1-5 seconds.
		dur := 1000 + rng.Intn(4000)
		if elapsed+dur > target {
			dur = target - elapsed
		}
		intervals = append(intervals, BandwidthInterval{
			DurationMs:    dur,
			BandwidthMbps: bw[state],
		})
		elapsed += dur
		// Transition.
		r := rng.Float64()
		cum := 0.0
		for next := 0; next < 3; next++ {
			cum += trans[state][next]
			if r <= cum {
				state = next
				break
			}
		}
	}
	return &BandwidthTrace{intervals: intervals}
}

// BandwidthAt returns the bandwidth in Mbps at offset t from trace start.
// For offsets past the end of the trace, the final interval's bandwidth is
// returned (trace extension).
func (bt *BandwidthTrace) BandwidthAt(t time.Duration) float64 {
	if len(bt.intervals) == 0 {
		return 0
	}
	ms := t.Milliseconds()
	acc := int64(0)
	for _, iv := range bt.intervals {
		acc += int64(iv.DurationMs)
		if ms < acc {
			return iv.BandwidthMbps
		}
	}
	return bt.intervals[len(bt.intervals)-1].BandwidthMbps
}

// TotalDuration returns the total trace length.
func (bt *BandwidthTrace) TotalDuration() time.Duration {
	// int64 accumulation guards against 32-bit int overflow for very long
	// traces (MED-8 fix).
	var acc int64
	for _, iv := range bt.intervals {
		acc += int64(iv.DurationMs)
	}
	return time.Duration(acc) * time.Millisecond
}
